apiVersion: v1
kind: Service
metadata:
  name: spring-app
spec:
  type: NodePort
  selector:
    app: spring-app
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30001  # Bu değeri istediğiniz gibi ayarlayabilirsiniz (30000-32767 aralığında)
